'use client'
import './globals.css'
import Navigation from '@/components/Navigation'
import { createContext, useEffect, useState } from 'react';
import { robotoFont, robotoHeavyFont } from './fonts';
import { isLoggedIn } from './actions';
/*
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
*/

export const AuthContext = createContext({
  user: null,
  setUser: () => { }
});

export const LocalizationContext = createContext({
  loc: 'en',
  setLoc: () => { }
});

export default function RootLayout({ children }) {
  const [user, setUser] = useState({});
  const providerValue = { user, setUser };

  const [loc, setLoc] = useState('en');
  const locProviderValue = { loc, setLoc };

  useEffect(() => {
    const checkLogin = async () => {
      const foundUser = await isLoggedIn();
      if (foundUser) setUser(foundUser);
    }

    checkLogin();
  }, []);

  return (
    <html lang="en">

      <body className="min-h-screen bg-[url('/background_paper_big.png')]">
        <AuthContext.Provider value={providerValue}>
          <LocalizationContext.Provider value={locProviderValue}>

            <Navigation className={`${robotoHeavyFont.className}`} />
            {children}
          </LocalizationContext.Provider>
        </AuthContext.Provider>
      </body>

    </html>
  )
}
